services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
#      MYSQL_USER: ${USER}
#      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

    ports:
      - "3307:3306"
    volumes:
      - db_data:/data/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DATABASE}
      SPRING_DATASOURCE_USERNAME: ${USER}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
volumes:
  db_data: